//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <SpringBoardFoundation/SBFTouchPassThroughView.h>

@class NSString, UIView;

@interface _SBMultiplexedHostView : SBFTouchPassThroughView
{
    NSString *_contextHostRequester;
    UIView *_hostView;
    UIView *_snapshotView;
    NSString *_requester;
}

@property(retain, nonatomic) UIView *snapshotView; // @synthesize snapshotView=_snapshotView;
@property(retain, nonatomic) UIView *hostView; // @synthesize hostView=_hostView;
@property(readonly, copy, nonatomic) NSString *requester; // @synthesize requester=_requester;
- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithRequester:(id)arg1;

@end

