//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <BulletinBoard/BBBulletinRequest.h>

@class NSString;

@interface BBBulletinRequest (SBBulletinBannerControllerTest)

// Remaining properties
@property(copy, nonatomic) NSString *bulletinID; // @dynamic bulletinID;
@end

