//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "FBSynchronizedTransactionDelegate-Protocol.h"

@class FBSynchronizedTransactionGroup, FBTransaction;
@protocol FBSynchronizedTransaction;

@protocol FBSynchronizedTransactionGroupDelegate <FBSynchronizedTransactionDelegate>

@optional
- (_Bool)synchronizedTransactionGroup:(FBSynchronizedTransactionGroup *)arg1 shouldFailForSynchronizedTransaction:(FBTransaction<FBSynchronizedTransaction> *)arg2;
@end

