//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NCNotificationAction, NSDictionary, NSString;

@protocol NCNotificationActionRunner <NSObject>
- (void)executeAction:(NCNotificationAction *)arg1 fromOrigin:(NSString *)arg2 withParameters:(NSDictionary *)arg3;
@end

