//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "BSDescriptionProviding-Protocol.h"
#import "SBAssertionDelegate-Protocol.h"

@class CPDistributedNotificationCenter, NSHashTable, NSMutableOrderedSet, NSMutableSet, NSString, SBAlertItemsObjectQueue;
@protocol SBAlertItemPresenter, SBAlertItemPresenter><SBLockScreenActionProvider;

@interface SBAlertItemsController : NSObject <SBAssertionDelegate, BSDescriptionProviding>
{
    SBAlertItemsObjectQueue *_alertItemsQueue;
    SBAlertItemsObjectQueue *_superModalItemsQueue;
    NSMutableOrderedSet *_alertItemPresentations;
    NSMutableOrderedSet *_superModalAlertItemPresentations;
    _Bool _inUILockedMode;
    NSMutableSet *_activePresenters;
    CPDistributedNotificationCenter *_notificationCenter;
    unsigned long long _notificationClientCount;
    _Bool _systemShuttingDown;
    NSMutableSet *_forceAlertsToPendReasons;
    NSHashTable *_observers;
    NSMutableSet *_suppressionAssertions;
    _Bool _modernLockScreenEnabled;
    _Bool _isProcessingQueue;
    _Bool _delayProcessingQueue;
    id <SBAlertItemPresenter><SBLockScreenActionProvider> _lockScreenModalAlertItemPresenter;
    id <SBAlertItemPresenter> _lockScreenNotificationsAlertItemPresenter;
    id <SBAlertItemPresenter> _unlockedAlertItemPresenter;
}

+ (id)sharedInstance;
@property(retain, nonatomic) id <SBAlertItemPresenter> unlockedAlertItemPresenter; // @synthesize unlockedAlertItemPresenter=_unlockedAlertItemPresenter;
@property(retain, nonatomic) id <SBAlertItemPresenter> lockScreenNotificationsAlertItemPresenter; // @synthesize lockScreenNotificationsAlertItemPresenter=_lockScreenNotificationsAlertItemPresenter;
@property(retain, nonatomic) id <SBAlertItemPresenter><SBLockScreenActionProvider> lockScreenModalAlertItemPresenter; // @synthesize lockScreenModalAlertItemPresenter=_lockScreenModalAlertItemPresenter;
- (void).cxx_destruct;
- (void)assertionExpired:(id)arg1;
- (_Bool)captureSuppressionAssertionWithPort:(unsigned int)arg1 reason:(id)arg2;
- (void)removeObserver:(id)arg1;
- (void)addObserver:(id)arg1;
- (void)_notifyObservers:(CDUnknownBlockType)arg1;
- (void)_activeCallStateDidChange:(id)arg1;
- (void)_buddyDidExit;
- (void)_notificationClientEnded:(id)arg1;
- (void)_notificationClientStarted:(id)arg1;
- (void)noteSystemShuttingDown;
- (void)moveActiveUnlockedAlertsToPendingWithAnimation:(_Bool)arg1;
- (void)setForceAlertsToPend:(_Bool)arg1 forReason:(id)arg2;
- (void)_postAlertPresentedNotificationForType:(int)arg1 sender:(id)arg2 date:(id)arg3;
- (void)noteVolumeOrLockPressedOverLockedAlerts;
- (void)stopPendingAlertItemsForFullscreenAlert;
- (void)deactivateAlertItemsForFullscreenAlertActivationAndPendMiniAlerts:(_Bool)arg1;
- (_Bool)dontLockOverAlertItems;
- (_Bool)deactivateAlertForMenuClickOrSystemGestureWithAnimation:(_Bool)arg1;
- (_Bool)canDeactivateAlertForMenuClickOrSystemGesture;
- (id)visibleAlertItem;
- (_Bool)hasVisibleSuperModalAlert;
- (_Bool)hasVisibleAlert;
- (_Bool)hasLockScreenModalAlert;
- (_Bool)hasAlerts;
- (_Bool)hasAlertOfClass:(Class)arg1;
- (id)alertItemsOfClass:(Class)arg1;
- (_Bool)deactivateAlertItemsOfClass:(Class)arg1 reason:(int)arg2 animated:(_Bool)arg3;
- (_Bool)deactivateAlertItemsOfClass:(Class)arg1 reason:(int)arg2;
- (_Bool)deactivateAlertItemsOfClass:(Class)arg1;
- (void)_enumeratePresentationsWithType:(unsigned long long)arg1 usingBlock:(CDUnknownBlockType)arg2;
- (id)_presentationForAlertItem:(id)arg1 presenter:(id)arg2 fromPresentations:(id)arg3;
- (void)_removePresentationForAlertItem:(id)arg1 presenter:(id)arg2;
- (void)_dismissAlertItem:(id)arg1 forReason:(int)arg2 animated:(_Bool)arg3;
- (void)_presentAlertItem:(id)arg1 animated:(_Bool)arg2;
- (id)_activePresenterForAlertItem:(id)arg1;
- (id)_presenterForAlertItem:(id)arg1;
- (_Bool)_shouldPendAlertItem:(id)arg1;
- (id)_presentedAlertItemForPresenter:(id)arg1;
- (_Bool)_hasPresentationForPresenter:(id)arg1;
- (void)_processAlertItemsFromQueue:(id)arg1 animated:(_Bool)arg2;
- (void)_processAlertItemQueuesAnimated:(_Bool)arg1;
- (_Bool)_canProcessAlertItem:(id)arg1;
- (void)_performBatchActions:(CDUnknownBlockType)arg1 animated:(_Bool)arg2 processQueue:(_Bool)arg3;
- (void)_updateActiveDestinations;
- (void)activatePendedAlertsIfNecessary;
- (void)deactivateAlertItem:(id)arg1 reason:(int)arg2 animated:(_Bool)arg3;
- (void)deactivateAlertItem:(id)arg1 reason:(int)arg2;
- (void)deactivateAlertItem:(id)arg1;
- (void)activateAlertItem:(id)arg1 animated:(_Bool)arg2;
- (void)activateAlertItem:(id)arg1;
- (void)convertLockedAlertsToUnlockedAlerts;
- (void)convertUnlockedAlertsToLockedAlerts;
- (void)setInUILockedMode:(_Bool)arg1;
- (id)descriptionBuilderWithMultilinePrefix:(id)arg1;
- (id)descriptionWithMultilinePrefix:(id)arg1;
- (id)succinctDescriptionBuilder;
- (id)succinctDescription;
@property(readonly, copy) NSString *description;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

