//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@interface SBAnimatableBlurEffectView : UIView
{
}

- (_Bool)_shouldAnimatePropertyWithKey:(id)arg1;
@property(nonatomic) double cornerRadius;
@property(nonatomic) double blurRadius;
- (id)initWithFrame:(struct CGRect)arg1;

@end

