//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "CCUIControlCenterSystemAgent-Protocol.h"

@class NSString;

@interface SBControlCenterSystemAgent : NSObject <CCUIControlCenterSystemAgent>
{
}

- (_Bool)isUILocked;
- (id)materialBackgroundView;
- (id)frontmostApplicationDisplayID;
- (id)getFGSceneIdentifiers;
- (_Bool)wifiIsPowered;
- (_Bool)wifiDevicePresent;
- (void)setWifiPowered:(_Bool)arg1;
- (void)updateWifiDevicePresence;
- (_Bool)isInAirplaneMode;
- (_Bool)isOrientationLocked;
- (void)unlockOrientation;
- (void)lockOrientation;
- (_Bool)wirelessDisplayRouteIsPicked;
- (id)nameOfPickedRoute;
- (_Bool)handsetRouteIsSelected;
- (void)setRingerMuted:(_Bool)arg1;
- (_Bool)isRingerMuted;
- (void)activateAppWithDisplayID:(id)arg1 url:(id)arg2;
- (void)dismissAnimated:(_Bool)arg1 completion:(CDUnknownBlockType)arg2;
- (id)prototypeSettings;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

