//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SBDashBoardModalViewControllerBase.h"

#import "SBDashBoardModalViewDelegate-Protocol.h"
#import "SBDashBoardNotificationDestination-Protocol.h"

@class NCNotificationAction, NCNotificationRequest, NSString;
@protocol SBDashBoardNotificationDispatcher;

@interface SBDashBoardFullscreenNotificationViewController : SBDashBoardModalViewControllerBase <SBDashBoardModalViewDelegate, SBDashBoardNotificationDestination>
{
    NCNotificationRequest *_request;
    NCNotificationAction *_primaryAction;
    NCNotificationAction *_secondaryAction;
    id <SBDashBoardNotificationDispatcher> _dispatcher;
}

@property(nonatomic) __weak id <SBDashBoardNotificationDispatcher> dispatcher; // @synthesize dispatcher=_dispatcher;
@property(readonly, nonatomic) NCNotificationRequest *notificationRequest; // @synthesize notificationRequest=_request;
- (void).cxx_destruct;
- (void)_dismissFromSignificantUserInteraction;
- (void)updateNotificationSectionSettings:(id)arg1;
- (void)withdrawNotificationRequest:(id)arg1;
- (void)updateNotificationRequest:(id)arg1;
- (void)postNotificationRequest:(id)arg1;
- (void)handleSecondaryActionForView:(id)arg1;
- (void)handlePrimaryActionForView:(id)arg1;
- (_Bool)wouldHandleButtonEvent:(id)arg1;
- (_Bool)handleEvent:(id)arg1;
- (long long)presentationPriority;
- (long long)presentationType;
- (void)_handleSecondaryActionAndDismiss;
- (void)_handlePrimaryActionAndDismiss;
- (void)loadView;
- (id)initWithNotificationRequest:(id)arg1;

// Remaining properties
@property(readonly, copy, nonatomic) NSString *dashBoardIdentifier;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly, nonatomic) long long participantState;
@property(readonly) Class superclass;

@end

