//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SBDashBoardViewTransitioning-Protocol.h"

@class SBApplication, SBDashBoardSlideUpToAppController, SBSlideUpAppGrabberView;

@protocol SBDashBoardSlideUpToAppControllerDelegate <SBDashBoardViewTransitioning>
- (SBSlideUpAppGrabberView *)slideControllerRequestedGrabberView:(SBDashBoardSlideUpToAppController *)arg1;
- (void)slideController:(SBDashBoardSlideUpToAppController *)arg1 requestedUnlockWithActionBlock:(void (^)(_Bool))arg2;
- (void)slideController:(SBDashBoardSlideUpToAppController *)arg1 didUpdateWithApplication:(SBApplication *)arg2;
- (_Bool)slideControllerShouldBeginSliding:(SBDashBoardSlideUpToAppController *)arg1;
- (long long)slideControllerRequestedInterfaceOrientation:(SBDashBoardSlideUpToAppController *)arg1;
@end

