//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SBDashBoardNowPlayingViewController.h"

@class MPULockScreenMediaControlsViewController;

@interface SBDashBoardMediaControlsViewController : SBDashBoardNowPlayingViewController
{
    MPULockScreenMediaControlsViewController *_mediaControlsViewController;
}

+ (Class)viewClass;
- (void).cxx_destruct;
- (void)_updatePersistentUpdateStateForBacklightValue:(double)arg1;
- (void)_layoutMediaControls;
- (_Bool)handleEvent:(id)arg1;
- (long long)presentationPriority;
- (long long)presentationType;
- (_Bool)shouldAutomaticallyForwardAppearanceMethods;
- (void)viewWillLayoutSubviews;
- (void)viewDidLoad;
- (id)initWithMediaControlsViewController:(id)arg1;

@end

