//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface SBDashBoardPowerChangeObserver : NSObject
{
    _Bool _connectedToPower;
    CDUnknownBlockType _block;
}

@property(copy, nonatomic) CDUnknownBlockType block; // @synthesize block=_block;
@property(nonatomic, getter=isConnectedToPower) _Bool connectedToPower; // @synthesize connectedToPower=_connectedToPower;
- (void).cxx_destruct;
- (void)setIsConnectedToPower:(_Bool)arg1;
- (void)update;
- (id)initWithBlock:(CDUnknownBlockType)arg1;

@end

