//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SBDashBoardPresentationViewController.h"

@interface SBDashBoardSlidingPresentationViewController : SBDashBoardPresentationViewController
{
    _Bool _dismissing;
}

- (_Bool)_dismissWithAnimation:(_Bool)arg1 completion:(CDUnknownBlockType)arg2;
- (_Bool)wouldHandleButtonEvent:(id)arg1;
- (_Bool)handleEvent:(id)arg1;
- (void)dismissPresentationAnimated:(_Bool)arg1 completion:(CDUnknownBlockType)arg2;
- (void)presentContentViewController:(id)arg1 animated:(_Bool)arg2 completion:(CDUnknownBlockType)arg3;
- (void)aggregateBehavior:(id)arg1;
- (void)aggregateAppearance:(id)arg1;

@end

