//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "SBMesaUnlockBehavior-Protocol.h"
#import "SBMesaUnlockTriggerDelegate-Protocol.h"

@class NSString, SBHomeHardwareButton, SBLockScreenMesaSettings, SBMesaUnlockTrigger;
@protocol SBMesaUnlockBehaviorDelegate;

@interface SBDashBoardMesaUnlockBehavior : NSObject <SBMesaUnlockTriggerDelegate, SBMesaUnlockBehavior>
{
    long long _failedMesaUnlockAttempts;
    SBLockScreenMesaSettings *_mesaSettings;
    SBHomeHardwareButton *_homeHardwareButton;
    id <SBMesaUnlockBehaviorDelegate> _mesaUnlockBehaviorDelegate;
    SBMesaUnlockTrigger *_trigger;
}

@property(nonatomic) __weak id <SBMesaUnlockBehaviorDelegate> mesaUnlockBehaviorDelegate; // @synthesize mesaUnlockBehaviorDelegate=_mesaUnlockBehaviorDelegate;
@property(readonly, nonatomic, getter=_mesaSettings) SBLockScreenMesaSettings *mesaSettings; // @synthesize mesaSettings=_mesaSettings;
@property(retain, nonatomic, getter=_trigger, setter=_setTrigger:) SBMesaUnlockTrigger *trigger; // @synthesize trigger=_trigger;
@property(retain, nonatomic, getter=_getHomeHardwareButton, setter=_setHomeHardwareButton:) SBHomeHardwareButton *homeHardwareButton; // @synthesize homeHardwareButton=_homeHardwareButton;
- (void).cxx_destruct;
- (id)_failureSettingsForFailAttempt:(long long)arg1;
- (void)_handleMesaFailure;
- (void)mesaUnlockTriggerFired:(id)arg1;
- (void)biometricEventMonitor:(id)arg1 handleBiometricEvent:(unsigned long long)arg2;
- (void)significantUserInteractionOccurred;
- (void)screenOff;
- (void)menuButtonUp;
- (void)menuButtonDown;
- (id)_feedbackForBioUnlockEventThatWasSpontaneous:(_Bool)arg1;
- (id)_feedbackForPasscodeEvent;
- (id)_feedbackForFailureSettings:(id)arg1;
- (id)_homeHardwareButton;
@property(readonly, copy) NSString *description;
- (id)initWithMesaSettings:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

