//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class SBDashBoardViewController, SBLockScreenUnlockRequest;

@protocol SBDashBoardViewControllerDelegate <NSObject>
- (void)dashBoardController:(SBDashBoardViewController *)arg1 unlockWithRequest:(SBLockScreenUnlockRequest *)arg2 completion:(void (^)(_Bool))arg3;
- (void)dashBoardViewControllerIrisPlayingDidFinish:(SBDashBoardViewController *)arg1;
@end

