//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SBDashBoardModalViewControllerBase.h"

#import "SBLockScreenEmergencyDialerDelegate-Protocol.h"

@class NSString, SBLockScreenEmergencyDialerController;

@interface SBDashBoardEmergencyDialerViewController : SBDashBoardModalViewControllerBase <SBLockScreenEmergencyDialerDelegate>
{
    SBLockScreenEmergencyDialerController *_controller;
}

- (void).cxx_destruct;
- (void)emergencyDialer:(id)arg1 willDeactivateWithError:(id)arg2;
- (long long)presentationPriority;
- (long long)presentationType;
- (void)aggregateBehavior:(id)arg1;
- (_Bool)handleEvent:(id)arg1;
- (void)_loadEmergencyDialerView;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)loadView;
- (void)dealloc;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

