//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SBDashBoardModalViewControllerBase.h"

#import "SBDashBoardModalViewDelegate-Protocol.h"

@class NSString;

@interface SBDashBoardTemperatureWarningViewController : SBDashBoardModalViewControllerBase <SBDashBoardModalViewDelegate>
{
}

- (void)handleSecondaryActionForView:(id)arg1;
- (long long)presentationPriority;
- (long long)presentationType;
- (void)aggregateAppearance:(id)arg1;
- (void)loadView;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

