//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "BSTransactionObserver-Protocol.h"
#import "SBAppViewHostRequester-Protocol.h"
#import "SBDashBoardAppearanceProviding-Protocol.h"
#import "SBDashBoardPasscodeViewControllerDelegate-Protocol.h"
#import "SBDashBoardViewTransitionSource-Protocol.h"
#import "UIGestureRecognizerDelegate-Protocol.h"
#import "_UISettingsKeyObserver-Protocol.h"

@class NSMutableArray, NSSet, NSString, NSURL, SBAppSuggestionManager, SBApplication, SBBestAppSuggestion, SBBounceSettings, SBDashBoardPasscodeViewController, SBLockScreenSettings, SBMainWorkspaceTransaction, SBNotificationCenterBounceAnimator, UIColor, UIPanGestureRecognizer, UIView, _UILegibilitySettings;
@protocol SBDashBoardSlideUpToAppControllerDelegate><SBDashBoardViewPresenting;

@interface SBDashBoardSlideUpToAppController : NSObject <UIGestureRecognizerDelegate, BSTransactionObserver, SBAppViewHostRequester, SBDashBoardPasscodeViewControllerDelegate, _UISettingsKeyObserver, SBDashBoardViewTransitionSource, SBDashBoardAppearanceProviding>
{
    SBLockScreenSettings *_testSettings;
    NSMutableArray *_deferredAppUpdateBlocks;
    _Bool _executingDeferredAppUpdateBlocks;
    double _currentYOffset;
    SBApplication *_targetApp;
    SBBestAppSuggestion *_targetAppInfo;
    NSURL *_targetURL;
    SBMainWorkspaceTransaction *_launchAppTransaction;
    UIView *_clippingView;
    UIView *_appDefaultImageView;
    UIView *_appBackgroundView;
    SBDashBoardPasscodeViewController *_passcodeViewController;
    UIPanGestureRecognizer *_slideUpToAppGestureRecognizer;
    SBBounceSettings *_bounceSettings;
    SBNotificationCenterBounceAnimator *_slideDownBounceAnimator;
    SBAppSuggestionManager *_appSuggestionManager;
    UIPanGestureRecognizer *_panGestureRecognizer;
    id <SBDashBoardSlideUpToAppControllerDelegate><SBDashBoardViewPresenting> _delegate;
    UIView *_containerView;
    unsigned long long _state;
}

@property(nonatomic, getter=_state, setter=_setState:) unsigned long long state; // @synthesize state=_state;
@property(retain, nonatomic) UIView *containerView; // @synthesize containerView=_containerView;
@property(nonatomic) __weak id <SBDashBoardSlideUpToAppControllerDelegate><SBDashBoardViewPresenting> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) UIPanGestureRecognizer *panGestureRecognizer; // @synthesize panGestureRecognizer=_panGestureRecognizer;
- (void).cxx_destruct;
- (void)_updateSlideUpToAppControllerWithCurrentSuggestedApp;
- (void)_suggestedAppDidChange:(id)arg1;
- (void)_deviceBlockedStateChanged:(id)arg1;
- (void)_passcodeLockStateChanged;
- (_Bool)_isPasscodeRequired;
- (void)_dismissPasscodeView;
- (void)_addOrRemovePasscodeViewIfNecessary;
- (void)_translateSlidingViewByY:(double)arg1;
- (void)_prepareForSlideUpAnimation;
- (void)_resetToInitialState;
- (void)_finishSlideDownGesture;
- (void)_finishSlideUpGesture;
- (id)_instantiateDynamicAnimationForTargetValue:(double)arg1 withInitialVelocity:(double)arg2;
- (void)_animateSlideUpWithVelocity:(struct CGPoint)arg1 completion:(CDUnknownBlockType)arg2;
- (void)_animateSlideDownWithVelocity:(struct CGPoint)arg1 completion:(CDUnknownBlockType)arg2;
- (void)_endSlideWithYTranslation:(double)arg1 velocty:(struct CGPoint)arg2 cancelled:(_Bool)arg3 completion:(CDUnknownBlockType)arg4;
- (void)_updateSlideWithYTranslation:(double)arg1;
- (void)_beginSlideWithYTranslation:(double)arg1;
- (void)_slideUpToAppRecognizerDidPan:(id)arg1;
- (struct CGRect)_slideUpToAppGrabberZoneForGrabber:(id)arg1;
- (void)_setSlideUpToAppGestureRecognizer:(id)arg1;
- (void)_setupSlideUpToAppGesture;
- (void)_activateApp:(id)arg1 withAppInfo:(id)arg2 andURL:(id)arg3 animated:(_Bool)arg4;
- (void)_activateTargetAppAnimated:(_Bool)arg1;
- (void)_executeDeferredAppUpdateBlocks;
- (void)_setTargetApp:(id)arg1 withAppSuggestion:(id)arg2;
- (void)_setupSubviews;
- (void)settings:(id)arg1 changedValueForKey:(id)arg2;
- (long long)appViewRequesterPriority:(id)arg1;
- (id)appViewRequesterIdentifier:(id)arg1;
@property(readonly, nonatomic) CDStruct_7238a68f transitionContext;
@property(readonly, nonatomic, getter=isTransitioning) _Bool transitioning;
@property(readonly, nonatomic) _UILegibilitySettings *legibilitySettings;
@property(readonly, copy, nonatomic) NSSet *components;
@property(readonly, nonatomic) UIColor *backgroundColor;
@property(readonly, nonatomic) long long backgroundStyle;
@property(readonly, copy, nonatomic) NSString *appearanceIdentifier;
@property(readonly, nonatomic) long long participantState;
@property(readonly, copy, nonatomic) NSString *dashBoardIdentifier;
- (void)passcodeViewController:(id)arg1 didCompletePasscodeEntry:(_Bool)arg2;
- (void)passcodeViewControllerDidCancelPasscodeEntry:(id)arg1;
- (void)passcodeViewControllerDidBeginPasscodeEntry:(id)arg1;
- (void)transactionDidComplete:(id)arg1;
- (void)transactionDidBegin:(id)arg1;
- (_Bool)gestureRecognizerShouldBegin:(id)arg1;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

