//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "SBDashBoardBackgroundStyleTransitioning-Protocol.h"
#import "SBDashBoardWallpaperOverlay-Protocol.h"

@class NSString, SBBackdropView;

@interface SBDashBoardBackgroundView : UIView <SBDashBoardBackgroundStyleTransitioning, SBDashBoardWallpaperOverlay>
{
    long long _style;
    long long _transitionStyle;
    _Bool _transitioning;
    double _progress;
    SBBackdropView *_backdropView;
    UIView *_sourceOverView;
    UIView *_darkenSourceOverView;
    UIView *_tintView;
}

@property(readonly, nonatomic, getter=isTransitioningBackgroundStyle) _Bool transitioningBackgroundStyle; // @synthesize transitioningBackgroundStyle=_transitioning;
@property(nonatomic) long long backgroundStyle; // @synthesize backgroundStyle=_style;
- (void).cxx_destruct;
- (void)_tintWithProgress:(double)arg1;
- (void)_darkenWithProgress:(double)arg1;
- (_Bool)_styleDarkens:(long long)arg1;
- (id)_backgroundColorForDarkenAlpha:(double)arg1 andProgress:(double)arg2;
- (void)completeTransitionToBackgroundStyle:(long long)arg1;
- (void)updateBackgroundStyleTransitionProgress:(double)arg1;
- (void)beginTransitionToBackgroundStyle:(long long)arg1;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

