//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIVisualEffectView;

@interface SBFolderControllerBackgroundView : UIView
{
    UIVisualEffectView *_blurView;
    UIView *_blurViewSnapshot;
    UIView *_reduceTransparencyTintView;
    _Bool _blurs;
    _Bool _expanding;
    _Bool _frozen;
    long long _style;
}

@property(nonatomic) _Bool frozen; // @synthesize frozen=_frozen;
@property(nonatomic) _Bool expanding; // @synthesize expanding=_expanding;
@property(nonatomic) _Bool blurs; // @synthesize blurs=_blurs;
@property(nonatomic) long long style; // @synthesize style=_style;
- (void).cxx_destruct;
- (void)_updateEffect;
- (id)_effectiveEmptyEffect;
- (id)_blurEffect;
- (void)layoutSubviews;
- (void)_updateForHavingReduceTransparencyOn:(_Bool)arg1;
- (void)_reduceTransparencyEnabledStateChanged;
- (id)initWithFrame:(struct CGRect)arg1;

@end

