//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableArray;
@protocol SBNotificationDestinationHomeButtonPressHandler;

@interface SBHomeHardwareButtonActions : NSObject
{
    _Bool _screenWasDimOnMenuDown;
    _Bool _dontUnlockOnButtonUp;
    _Bool _isButtonDown;
    _Bool _isGuidedAccessActive;
    NSMutableArray *_menuButtonUpBlocks;
    NSMutableArray *_menuButtonUpHandledBlocks;
    unsigned long long _menuButtonHoldStartTime;
    double _menuButtonHoldStartAbsoluteTime;
    double _currentLongPressDuration;
    id <SBNotificationDestinationHomeButtonPressHandler> _bannerDestination;
    id <SBNotificationDestinationHomeButtonPressHandler> _notificationCenterDestination;
}

@property(nonatomic) __weak id <SBNotificationDestinationHomeButtonPressHandler> notificationCenterDestination; // @synthesize notificationCenterDestination=_notificationCenterDestination;
@property(nonatomic) __weak id <SBNotificationDestinationHomeButtonPressHandler> bannerDestination; // @synthesize bannerDestination=_bannerDestination;
@property(nonatomic) double currentLongPressDuration; // @synthesize currentLongPressDuration=_currentLongPressDuration;
- (void).cxx_destruct;
- (void)_logMenuButtonHoldTime;
- (void)_performMenuButtonUpHandledBlocks;
- (void)performAfterMenuButtonUpIsHandledUsingBlock:(CDUnknownBlockType)arg1;
- (void)_performMenuButtonIsUpBlocks;
- (void)performWhenMenuButtonIsUpUsingBlock:(CDUnknownBlockType)arg1;
- (void)_cancelPreheatingOfPlugin;
- (void)_preheatPluginForPresentationAfterInterval:(double)arg1;
- (void)performDoubleTapUpActions;
- (void)performLongPressCancelledActions;
- (void)performFinalButtonUpActions;
- (void)performTriplePressUpActions;
- (void)performDoublePressDownActions;
- (void)performLongPressActions;
- (void)performSinglePressUpActions;
- (_Bool)_shouldIgnorePressesDueToProxOrIdle;
- (void)performSinglePressHintAction:(id)arg1;
- (_Bool)_performButtonPreflightActions;
- (void)performInitialButtonDownActions;
- (void)guidedAccessWasDeactivated;
- (void)guidedAccessWasActivated;
- (id)init;

@end

