//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "SBAlertManagerObserver-Protocol.h"
#import "UIGestureRecognizerDelegate-Protocol.h"

@class BKSButtonDefinition, NSMutableDictionary, NSString, SBHomeHardwareButtonActions, SBHomeHardwareButtonGestureRecognizerConfiguration, UIGestureRecognizer;
@protocol SBNotificationDestinationHomeButtonPressHandler;

@interface SBHomeHardwareButton : NSObject <UIGestureRecognizerDelegate, SBAlertManagerObserver>
{
    _Bool _longPressDidOccur;
    id <SBNotificationDestinationHomeButtonPressHandler> _bannerDestination;
    id <SBNotificationDestinationHomeButtonPressHandler> _notificationCenterDestination;
    SBHomeHardwareButtonActions *_buttonActions;
    SBHomeHardwareButtonGestureRecognizerConfiguration *_gestureRecognizerConfiguration;
    UIGestureRecognizer *_screenshotGestureRecognizer;
    long long _maximumPressCount;
    long long _maximumTapCount;
    double _longPressDurationOverride;
    NSMutableDictionary *_emulatedPerSenderDownCount;
    BKSButtonDefinition *_buttonDefinition;
}

@property(retain, nonatomic) BKSButtonDefinition *buttonDefinition; // @synthesize buttonDefinition=_buttonDefinition;
@property(retain, nonatomic) NSMutableDictionary *emulatedPerSenderDownCount; // @synthesize emulatedPerSenderDownCount=_emulatedPerSenderDownCount;
@property(nonatomic) _Bool longPressDidOccur; // @synthesize longPressDidOccur=_longPressDidOccur;
@property(nonatomic) double longPressDurationOverride; // @synthesize longPressDurationOverride=_longPressDurationOverride;
@property(nonatomic) long long maximumTapCount; // @synthesize maximumTapCount=_maximumTapCount;
@property(nonatomic) long long maximumPressCount; // @synthesize maximumPressCount=_maximumPressCount;
@property(nonatomic) __weak UIGestureRecognizer *screenshotGestureRecognizer; // @synthesize screenshotGestureRecognizer=_screenshotGestureRecognizer;
@property(retain, nonatomic) SBHomeHardwareButtonGestureRecognizerConfiguration *gestureRecognizerConfiguration; // @synthesize gestureRecognizerConfiguration=_gestureRecognizerConfiguration;
@property(retain, nonatomic) SBHomeHardwareButtonActions *buttonActions; // @synthesize buttonActions=_buttonActions;
@property(nonatomic) __weak id <SBNotificationDestinationHomeButtonPressHandler> notificationCenterDestination; // @synthesize notificationCenterDestination=_notificationCenterDestination;
@property(nonatomic) __weak id <SBNotificationDestinationHomeButtonPressHandler> bannerDestination; // @synthesize bannerDestination=_bannerDestination;
- (void).cxx_destruct;
- (_Bool)_isMenuDoublePressAllowed:(id *)arg1;
- (_Bool)_isMenuDoublePressDisabled;
- (void)_cancelGestureRecognizer:(id)arg1;
- (void)singlePressHint:(id)arg1;
- (void)alertManager:(id)arg1 didChangeTopAlertFromAlert:(id)arg2 toAlert:(id)arg3;
- (void)doubleTapUp:(id)arg1;
- (void)triplePressUp:(id)arg1;
- (void)doublePressUp:(id)arg1;
- (void)doublePressDown:(id)arg1;
- (_Bool)_processDoubleDownAndDoubleUpSimultaneously;
- (void)longPress:(id)arg1;
- (void)singlePressUp:(id)arg1;
- (void)acceleratedSinglePressUp:(id)arg1;
- (void)_singlePressUp:(id)arg1;
- (void)buttonDown:(id)arg1;
- (_Bool)emulateHomeButtonEventsIfNeeded:(struct __IOHIDEvent *)arg1;
- (void)_terminateHomeButtonEventAtCount:(long long)arg1;
- (_Bool)gestureRecognizerShouldBegin:(id)arg1;
- (_Bool)_hintRecognizerShouldBegin;
- (_Bool)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2;
- (void)cancelLongPress;
- (void)performAfterMenuButtonUpIsHandledUsingBlock:(CDUnknownBlockType)arg1;
- (void)performWhenMenuButtonIsUpUsingBlock:(CDUnknownBlockType)arg1;
- (void)_reconfigureGestureRecognizersForNewMaximumPressCount:(long long)arg1 oldMaximumPressCount:(long long)arg2;
- (void)_reconfigureGestureRecognizersForNewMaximumTapCount:(long long)arg1 oldMaximumTapCount:(long long)arg2;
- (void)_createGestureRecognizersWithConfiguration:(id)arg1;
- (void)setLongPressDuration:(double)arg1;
- (void)_reconfigureHomeButton;
- (void)_startObservingReconfigurationTriggers;
- (id)initWithScreenshotGestureRecognizer:(id)arg1 buttonActions:(id)arg2 gestureRecognizerConfiguration:(id)arg3;
- (id)initWithScreenshotGestureRecognizer:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

