//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SBIconImageAppCrossfadeView.h"

@class SBAnimatableBlurEffectView;

@interface SBIconImageAppHighQualityCrossfadeView : SBIconImageAppCrossfadeView
{
    SBAnimatableBlurEffectView *_imageViewEffectView;
    SBAnimatableBlurEffectView *_crossfadeViewEffectView;
}

- (void).cxx_destruct;
- (void)cleanup;
- (void)setAppSnapshotBlurFraction:(double)arg1;
- (void)setIconBlurFraction:(double)arg1;
- (double)iconBlurRadiusForFraction:(double)arg1;
- (double)crossfadeBlurRadiusForFraction:(double)arg1;
- (void)applyCornerRadius:(double)arg1;
- (id)crossfadeViewParentView;
- (id)imageViewParentView;

@end

