//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "BSDescriptionProviding-Protocol.h"
#import "NSCopying-Protocol.h"
#import "NSObject-Protocol.h"

@protocol SBIdleTimer, SBIdleTimerDelegate;

@protocol SBIdleTimer <NSObject, NSCopying, BSDescriptionProviding>
@property(nonatomic) __weak id <SBIdleTimerDelegate> delegate;
- (_Bool)isEqualToTimer:(id <SBIdleTimer>)arg1;
- (void)reset;
@end

