//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@protocol SBLayoutContext <NSObject>
@property(readonly, nonatomic) long long interfaceOrientation;
- (_Bool)layoutContainsRole:(long long)arg1;
@end

