//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@class SBLiftToWakeController;

@protocol SBLiftToWakeObserver
- (void)liftToWakeController:(SBLiftToWakeController *)arg1 didObserveTransition:(long long)arg2;
@end

