//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "SBLiftToWakeObserver-Protocol.h"

@class SBBacklightController, SBIdleTimerDefaults, SBLiftToWakeController, SBLockScreenManager, SBPolicyAggregator;

@interface SBLiftToWakeManager : NSObject <SBLiftToWakeObserver>
{
    SBLiftToWakeController *_liftToWakeController;
    SBLockScreenManager *_lockScreenManager;
    SBBacklightController *_backlightController;
    SBIdleTimerDefaults *_idleTimerDefaults;
    SBPolicyAggregator *_policyAggregator;
    _Bool _gestureWokeScreen;
    _Bool _observing;
}

@property(nonatomic, getter=_gestureWokeScreen, setter=_setGestureWokeScreen:) _Bool gestureWokeScreen; // @synthesize gestureWokeScreen=_gestureWokeScreen;
@property(retain, nonatomic, getter=_backlightController, setter=_setBacklightController:) SBBacklightController *backlightController; // @synthesize backlightController=_backlightController;
@property(retain, nonatomic, getter=_lockScreenManager, setter=_setLockScreenManager:) SBLockScreenManager *lockScreenManager; // @synthesize lockScreenManager=_lockScreenManager;
@property(retain, nonatomic, getter=_policyAggregator, setter=_setPolicyAggregator:) SBPolicyAggregator *policyAggregator; // @synthesize policyAggregator=_policyAggregator;
@property(retain, nonatomic, getter=_idleTimerDefaults, setter=_setIdleTimerDefaults:) SBIdleTimerDefaults *idleTimerDefaults; // @synthesize idleTimerDefaults=_idleTimerDefaults;
@property(retain, nonatomic, getter=_liftToWakeController, setter=_setLiftToWakeController:) SBLiftToWakeController *liftToWakeController; // @synthesize liftToWakeController=_liftToWakeController;
- (void).cxx_destruct;
- (void)liftToWakeController:(id)arg1 didObserveTransition:(long long)arg2;
- (void)_stopObservingIfNecessary;
- (void)_startObservingIfNecessary;
- (_Bool)_isLockScreenMainPageVisible;
- (void)_ignoredTransition:(long long)arg1;
- (void)_reloadLiftToWakeSupport;
- (void)_backlightWillTurnOn:(id)arg1;
- (id)description;
- (void)dealloc;
- (id)initWithLiftToWakeController:(id)arg1 idleTimerDefaults:(id)arg2;
- (id)init;

@end

