//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "CMWakeGestureDelegate-Protocol.h"

@class CMWakeGestureManager, NSHashTable, NSString;

@interface SBLiftToWakeController : NSObject <CMWakeGestureDelegate>
{
    _Bool _screenOn;
    CMWakeGestureManager *_wakeGestureManager;
    NSHashTable *_observers;
    long long _wakeGestureState;
}

+ (id)sharedController;
+ (_Bool)isLiftToWakeAvailable;
@property(nonatomic) long long wakeGestureState; // @synthesize wakeGestureState=_wakeGestureState;
@property(retain, nonatomic) NSHashTable *observers; // @synthesize observers=_observers;
@property(retain, nonatomic) CMWakeGestureManager *wakeGestureManager; // @synthesize wakeGestureManager=_wakeGestureManager;
- (void).cxx_destruct;
- (void)wakeGestureManager:(id)arg1 didUpdateWakeGesture:(long long)arg2;
- (void)_sendTransitionToObservers:(long long)arg1;
- (void)_stopObservingIfNecessary;
- (void)_startObservingIfNecessary;
- (void)_handleBacklightLevelChanged:(id)arg1;
- (void)_screenTurnedOn;
- (void)_screenTurnedOff;
- (void)_ignoredTransition:(long long)arg1;
- (void)removeObserver:(id)arg1;
- (void)addObserver:(id)arg1;
@property(readonly, copy) NSString *description;
- (id)initWithBacklightController:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

