//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <SpringBoardFoundation/SBFLockScreenDateSubtitleView.h>

@class NSDate;

@interface SBLockScreenTimerView : SBFLockScreenDateSubtitleView
{
    NSDate *_endDate;
}

- (void).cxx_destruct;
- (id)_timerFont;
- (id)_newTimerDialForSettings:(id)arg1;
- (void)updateTimerLabel;
- (void)setEndDate:(id)arg1;
- (void)setLegibilitySettings:(id)arg1;
- (id)init;

@end

