//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SBUIBiometricEventObserver-Protocol.h"

@protocol SBMesaUnlockBehaviorDelegate;

@protocol SBMesaUnlockBehavior <SBUIBiometricEventObserver>
@property(nonatomic) __weak id <SBMesaUnlockBehaviorDelegate> mesaUnlockBehaviorDelegate;
@end

