//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface SBMesaUnlockFeedback : NSObject
{
    unsigned long long _vibration;
    _Bool _showPasscode;
    _Bool _jiggleLock;
}

@property(nonatomic) _Bool jiggleLock; // @synthesize jiggleLock=_jiggleLock;
@property(nonatomic) unsigned long long vibration; // @synthesize vibration=_vibration;
@property(nonatomic) _Bool showPasscode; // @synthesize showPasscode=_showPasscode;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (id)description;

@end

