//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NCNotificationDestination-Protocol.h"
#import "SBNotificationSectionSettingsObserver-Protocol.h"

@class NSString, SBNotificationSectionSettings;
@protocol BBObserverDelegate, NCNotificationDestinationDelegate;

@interface SBNotificationLegacyListDestination : NSObject <SBNotificationSectionSettingsObserver, NCNotificationDestination>
{
    id <NCNotificationDestinationDelegate> _delegate;
    id <BBObserverDelegate> _bbObserverDelegate;
    unsigned long long _feed;
    SBNotificationSectionSettings *_sectionSettings;
}

@property(retain, nonatomic) SBNotificationSectionSettings *sectionSettings; // @synthesize sectionSettings=_sectionSettings;
@property(nonatomic) unsigned long long feed; // @synthesize feed=_feed;
@property(retain, nonatomic) id <BBObserverDelegate> bbObserverDelegate; // @synthesize bbObserverDelegate=_bbObserverDelegate;
@property(nonatomic) __weak id <NCNotificationDestinationDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)updateSectionInfo:(id)arg1;
- (void)updateSectionOrder:(id)arg1;
- (void)updateSectionOrderRule:(long long)arg1;
- (void)withdrawNotificationRequest:(id)arg1 forCoalescedNotification:(id)arg2;
- (void)modifyNotificationRequest:(id)arg1 forCoalescedNotification:(id)arg2;
- (void)postNotificationRequest:(id)arg1 forCoalescedNotification:(id)arg2;
- (_Bool)canReceiveNotificationRequest:(id)arg1;
@property(readonly, nonatomic) NSString *identifier;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

