//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SBSearchEtceteraMultiplexingViewController.h"

@class NCNotificationListViewController, SBSearchEtceteraNavigationController, UIPageControl, UIView;
@protocol SBNotificationCenterWithSearchViewControllerPresentationDelegate;

@interface SBNotificationCenterWithSearchViewController : SBSearchEtceteraMultiplexingViewController
{
    id <SBNotificationCenterWithSearchViewControllerPresentationDelegate> _presentationDelegate;
}

@property(nonatomic) __weak id <SBNotificationCenterWithSearchViewControllerPresentationDelegate> presentationDelegate; // @synthesize presentationDelegate=_presentationDelegate;
- (void).cxx_destruct;
- (void)performScrollTest:(id)arg1 iterations:(long long)arg2 delta:(long long)arg3;
- (void)willActivateHosting;
- (id)customAnimator;
- (id)requestedLegibilitySettings;
- (unsigned long long)presentationMode;
- (unsigned long long)initialPresentationMode;
- (unsigned long long)defaultSearchViewDismissalReason;
- (unsigned long long)defaultSearchViewPresentationSource;
- (void)didChangeToMode:(unsigned long long)arg1 animated:(_Bool)arg2;
- (void)willChangeToMode:(unsigned long long)arg1 animated:(_Bool)arg2;
@property(readonly, nonatomic) UIPageControl *pageControl;
- (void)updateClippingLineVisibility;
- (void)exitSpotlightAnimated:(_Bool)arg1 completion:(CDUnknownBlockType)arg2;
- (void)enterSpotlightAnimated:(_Bool)arg1 fromPartialPulldown:(_Bool)arg2 completion:(CDUnknownBlockType)arg3;
@property(readonly, nonatomic) UIView *contentContainerView;
@property(readonly, nonatomic) UIView *notificationContentView;
@property(readonly, nonatomic) NCNotificationListViewController *notificationListViewController;
@property(readonly, nonatomic) SBSearchEtceteraNavigationController *navigationController;
- (id)init;

@end

