//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@protocol SBPassKitPrearmTriggerDelegate;

@interface SBPassKitPrearmTrigger : NSObject
{
    id <SBPassKitPrearmTriggerDelegate> _delegate;
    double _baseFingerDownTimeout;
    double _fingerDownTimeout;
    _Bool _fingerOnTimerActive;
}

- (void).cxx_destruct;
- (double)_accessibilityModifyTimeoutForHomeClickSpeed:(double)arg1;
- (void)accessibilityHomeClickTimeoutsChanged;
- (void)accessibilityCancelFingerOnTimer;
- (void)menuButtonDoublePress;
- (void)menuButtonSinglePress;
- (void)fingerOn;
- (_Bool)isTrackingUserInput;
- (void)_reset;
- (void)dealloc;
- (id)initWithDelegate:(id)arg1 fingerDownTimeout:(double)arg2;

@end

