//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <PrototypeTools/PTSRowTableViewCell.h>

@interface SBReadonlyTableViewCell : PTSRowTableViewCell
{
}

+ (long long)cellStyleForRow:(id)arg1;
- (void)updateDisplayedValue;

@end

