//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIImageView.h>

@interface SBSaturatedIconView : UIImageView
{
}

- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (id)initWithImage:(id)arg1;
- (id)initWithApplication:(id)arg1 iconFormat:(int)arg2;

@end

