//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SBIconZoomSettings.h"

@class SBAnimationSettings;

@interface SBScaleZoomSettings : SBIconZoomSettings
{
    _Bool _useTwoPhases;
    _Bool _crossfadeWithZoom;
    double _phaseOneTargetFraction;
    double _phaseTwoDelay;
    SBAnimationSettings *_phaseOneSettings;
    SBAnimationSettings *_outerFolderFadeSettings;
    SBAnimationSettings *_crossfadeSettings;
}

+ (id)settingsControllerModule;
@property(retain) SBAnimationSettings *crossfadeSettings; // @synthesize crossfadeSettings=_crossfadeSettings;
@property _Bool crossfadeWithZoom; // @synthesize crossfadeWithZoom=_crossfadeWithZoom;
@property(retain) SBAnimationSettings *outerFolderFadeSettings; // @synthesize outerFolderFadeSettings=_outerFolderFadeSettings;
@property(retain) SBAnimationSettings *phaseOneSettings; // @synthesize phaseOneSettings=_phaseOneSettings;
@property double phaseTwoDelay; // @synthesize phaseTwoDelay=_phaseTwoDelay;
@property double phaseOneTargetFraction; // @synthesize phaseOneTargetFraction=_phaseOneTargetFraction;
@property _Bool useTwoPhases; // @synthesize useTwoPhases=_useTwoPhases;
- (void).cxx_destruct;
- (id)centralAnimationSettingsWithAdditionalDelays;
- (id)phaseTwoSettings;
- (id)effectiveCrossfadeAnimationSettings;
- (void)setDefaultValues;

@end

