//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableArray, NSMutableDictionary;

@interface SBScreenManager : NSObject
{
    NSMutableArray *_handlers;
    NSMutableDictionary *_screenIDToHandlerMap;
    NSMutableDictionary *_screenIDToLastDisplayMap;
}

+ (id)sharedInstance;
- (void).cxx_destruct;
- (void)addConnectionHandler:(id)arg1;
- (id)lastDisplayForScreen:(id)arg1;
- (id)lastDisplayForScreenWithID:(unsigned int)arg1;
- (void)_screenDidDisconnect:(id)arg1;
- (void)_screenDidConnect:(id)arg1;
- (void)_updateHandlerForConnectionToScreen:(id)arg1;
- (id)init;

@end

