//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class SBSearchEtceteraLayoutView;

@protocol SBSearchEtceteraLayoutViewDelegate <NSObject>

@optional
- (void)searchEtceteraLayoutView:(SBSearchEtceteraLayoutView *)arg1 currentModeDidChange:(unsigned long long)arg2;
@end

