//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface SBSearchEtceteraMetrics : NSObject
{
}

+ (_Bool)_isPortrait;
+ (double)minYofClippableContent;
+ (_Bool)shouldShowWeatherViewForStyle:(unsigned long long)arg1;
+ (double)topContentInsetForSearchNavigationBar:(id)arg1;
+ (_Bool)shouldAddNavBarInsetForStyle:(unsigned long long)arg1;
+ (_Bool)shouldAddTopInsetForStyle:(unsigned long long)arg1;
+ (_Bool)isShowingTwoWidgetColumns;

@end

