//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@interface SBSearchEtceteraLayoutContentView : UIView
{
    _Bool _didConfigureBlurFilter;
    unsigned long long _currentStyle;
    double _inputRadius;
}

+ (id)_inputRadiusKeyPath;
@property(nonatomic) unsigned long long currentStyle; // @synthesize currentStyle=_currentStyle;
@property(nonatomic) double blurInputRadius; // @synthesize blurInputRadius=_inputRadius;
- (struct CGSize)contentSizeForContainerSize:(struct CGSize)arg1;
- (_Bool)_shouldAnimatePropertyWithKey:(id)arg1;
- (void)_configureBlurFilterIfNecessary;

@end

