//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class SBWindow;

@interface SBSetupManager : NSObject
{
    _Bool _inSetupMode;
    SBWindow *_setupLogoWindow;
    _Bool _fromOTASoftwareUpdate;
}

+ (id)sharedInstance;
@property(nonatomic) _Bool fromOTASoftwareUpdate; // @synthesize fromOTASoftwareUpdate=_fromOTASoftwareUpdate;
- (void).cxx_destruct;
- (_Bool)_setInSetupMode:(_Bool)arg1;
- (void)hideSetupLogoForSetupLaunchComplete;
- (void)showSetupLogoForSetupLaunch;
@property(readonly, nonatomic, getter=isShowingSetupLogo) _Bool showingSetupLogo; // @dynamic showingSetupLogo;
@property(readonly, nonatomic, getter=isSetupLogoBlack) _Bool setupLogoBlack; // @dynamic setupLogoBlack;
- (_Bool)setupIsRunningForUpdateInstall;
- (_Bool)setupHasFinishedRestoringFromBackup;
- (_Bool)updateInSetupMode;
@property(readonly, nonatomic, getter=isInSetupMode) _Bool inSetupMode;
- (id)init;

@end

