//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class SBSearchEtceteraIsolatedViewController, _UILegibilitySettings;
@protocol SBSearchEtceteraIsolatedViewControllerAnimatedTransitioning;

@protocol SBSearchEtceteraIsolatedViewControllerAppearanceDelegate <NSObject>

@optional
- (void)searchEtceteraIsolatedViewController:(SBSearchEtceteraIsolatedViewController *)arg1 didChangeToMode:(unsigned long long)arg2 animated:(_Bool)arg3;
- (void)searchEtceteraIsolatedViewController:(SBSearchEtceteraIsolatedViewController *)arg1 changingToMode:(unsigned long long)arg2 animated:(_Bool)arg3;
- (void)searchEtceteraIsolatedViewController:(SBSearchEtceteraIsolatedViewController *)arg1 willChangeToMode:(unsigned long long)arg2 animated:(_Bool)arg3;
- (id <SBSearchEtceteraIsolatedViewControllerAnimatedTransitioning>)customAnimator;
- (long long)requestedWallpaperVariantForWidgetBackgroundViews;
- (_UILegibilitySettings *)requestedLegibilitySettings;
@end

