//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "SBUILegibility-Protocol.h"
#import "_SBFVibrantView-Protocol.h"

@class NSString, SBSaturatedIconView, SBUILegibilityView, UIImage, _SBFVibrantSettings, _UILegibilitySettings;
@protocol SBResponderTouchDelegate;

@interface SBSlideUpAppGrabberView : UIView <_SBFVibrantView, SBUILegibility>
{
    double _strength;
    _UILegibilitySettings *_legibilitySettings;
    struct UIEdgeInsets _hitTestEdgeInsets;
    UIView *_tintView;
    UIView *_backgroundView;
    SBUILegibilityView *_legibilityView;
    SBSaturatedIconView *_saturatedIconView;
    UIImage *_grabberImage;
    _Bool _vibrancyAllowed;
    _SBFVibrantSettings *_vibrantSettings;
    id <SBResponderTouchDelegate> _delegate;
}

@property(nonatomic, getter=isVibrancyAllowed) _Bool vibrancyAllowed; // @synthesize vibrancyAllowed=_vibrancyAllowed;
@property(nonatomic) __weak id <SBResponderTouchDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) _UILegibilitySettings *legibilitySettings; // @synthesize legibilitySettings=_legibilitySettings;
@property(nonatomic) double strength; // @synthesize strength=_strength;
@property(retain, nonatomic) _SBFVibrantSettings *vibrantSettings; // @synthesize vibrantSettings=_vibrantSettings;
@property(readonly, nonatomic) struct UIEdgeInsets hitTestEdgeInsets; // @synthesize hitTestEdgeInsets=_hitTestEdgeInsets;
- (void).cxx_destruct;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)touchesCancelled:(id)arg1 withEvent:(id)arg2;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (id)_lazyLegibilityView;
- (void)setBackgroundView:(id)arg1;
- (_Bool)_shouldUseVibrancy;
- (void)setAppStyleGrabberImage:(id)arg1;
- (void)setGrabberImageFromApp:(id)arg1 withIconFormat:(int)arg2;
- (void)setGrabberImageFromApp:(id)arg1;
- (void)setGrabberImage:(id)arg1;
- (void)setBackgroundColor:(id)arg1;
- (void)layoutSubviews;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (_Bool)pointInside:(struct CGPoint)arg1 withEvent:(id)arg2;
- (void)dealloc;
- (id)initWithAdditionalTopPadding:(_Bool)arg1 invertVerticalInsets:(_Bool)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

