//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SBStartupTransitionToLockOut.h"

@interface SBStartupTransitionToLoginWindow : SBStartupTransitionToLockOut
{
}

- (void)performTransitionWithCompletionBlock:(CDUnknownBlockType)arg1;
- (id)suggestedLockAnimationForTransitionRequest:(id)arg1;

@end

