//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SBUIMainScreenAnimationController.h"

@class SBAlert, SBMainAlertManager, SBRemoteAlertAdapter;

@interface SBUIAnimationRemoteAlertToAlert : SBUIMainScreenAnimationController
{
    SBRemoteAlertAdapter *_remoteAlert;
    SBAlert *_toAlert;
    SBMainAlertManager *_alertManager;
    _Bool _initialFakeStatusBarNeeded;
    double _animationDuration;
}

- (void).cxx_destruct;
- (void)_animationFinished;
- (void)_cleanupAnimation;
- (void)_startAnimation;
- (void)_prepareAnimation;
- (id)animationSettings;
- (double)animationDuration;
- (id)initWithTransitionContextProvider:(id)arg1;

@end

