//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SBUIAnimationZoomApp.h"

#import "SBTreeNodeViewControllerTransitionObserver-Protocol.h"
#import "SBViewControllerReversibleAnimatedTransitioning-Protocol.h"

@class NSString, SBAppView, SBLeafIcon;
@protocol SBViewControllerContextTransitioning;

@interface SBUIAnimationHomeScreenZoomApp : SBUIAnimationZoomApp <SBViewControllerReversibleAnimatedTransitioning, SBTreeNodeViewControllerTransitionObserver>
{
    id <SBViewControllerContextTransitioning> _transitionContext;
    SBLeafIcon *_transitioningIcon;
    SBAppView *_transitioningAppView;
    CDUnknownBlockType _homeScreenTransitionCompletion;
    _Bool _homeScreenTransitionFinishedCancelled;
    _Bool _finishedZooming;
    _Bool _attemptingCrossfade;
    _Bool _finishedCrossfadingToHostView;
    _Bool _finishedActivating;
    _Bool _activationFailed;
}

@property(retain, nonatomic) SBLeafIcon *transitioningIcon; // @synthesize transitioningIcon=_transitioningIcon;
- (void).cxx_destruct;
- (void)_maybeReportAnimationFinished;
- (void)_maybeStartCrossfade;
- (_Bool)_delaysLiveContentUntilZoomFinished;
- (void)_configureAppView:(id)arg1 forZoomDirection:(unsigned long long)arg2;
- (void)treeNodeViewController:(id)arg1 willPerformOperation:(long long)arg2 fromViewController:(id)arg3 fromIndexPath:(id)arg4 toViewController:(id)arg5 toIndexPath:(id)arg6 withTransitionCoordinator:(id)arg7;
- (void)animationEnded:(_Bool)arg1;
- (_Bool)supportsRestarting;
- (void)cancelTransition:(id)arg1 withCompletionSpeed:(double)arg2 completionCurve:(long long)arg3;
- (void)animateTransition:(id)arg1;
- (id)transitionAnimationFactory:(id)arg1;
- (double)transitionDuration:(id)arg1;
- (void)_applicationDependencyStateChanged;
- (void)_cleanupAnimation;
- (id)_transitionAnimator;
- (void)_prepareAnimation;
- (_Bool)_pastPointOfNoReturn;
- (_Bool)transitionSupportsCancelling;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

