//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "UIScrollViewDelegate-Protocol.h"

@class UIScrollView, UIView, WGWidgetGroupViewController;

@protocol WGWidgetGroupViewControllerDelegate <UIScrollViewDelegate>

@optional
- (UIView *)widgetGroupViewController:(WGWidgetGroupViewController *)arg1 newCustomBackgroundViewForItem:(id)arg2 inScrollView:(UIScrollView *)arg3;
@end

